
package com.my.project.service.bare.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "userService", targetNamespace = "http://service.project.my.com/user")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param user
     */
    @WebMethod(action = "http://service.project.my.com/user/add")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void add(
        @WebParam(name = "user", targetNamespace = "http://service.project.my.com/user", partName = "user")
        User user);

    /**
     * 
     * @param username
     */
    @WebMethod(action = "http://service.project.my.com/user/delete")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void delete(
        @WebParam(name = "username", targetNamespace = "http://service.project.my.com/user", partName = "username")
        String username);

    /**
     * 
     * @return
     *     returns com.my.project.service.bare.client.UserList
     */
    @WebMethod(action = "http://service.project.my.com/user/list")
    @WebResult(name = "userList", targetNamespace = "http://service.project.my.com/user", partName = "userList")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UserList list();

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.my.project.service.bare.client.User
     */
    @WebMethod(action = "http://service.project.my.com/user/login")
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.project.my.com/user", className = "com.my.project.service.bare.client.Login")
    @ResponseWrapper(localName = "loginUser", targetNamespace = "http://service.project.my.com/user", className = "com.my.project.service.bare.client.LoginUser")
    public User login(
        @WebParam(name = "username", targetNamespace = "http://service.project.my.com/user")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
