
package com.my.project.service.rpc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "userService", targetNamespace = "http://service.project.my.com/user")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param user
     */
    @WebMethod(action = "http://service.project.my.com/user/add")
    public void add(
        @WebParam(name = "user", partName = "user")
        User user);

    /**
     * 
     * @param username
     */
    @WebMethod(action = "http://service.project.my.com/user/delete")
    public void delete(
        @WebParam(name = "username", partName = "username")
        String username);

    /**
     * 
     * @return
     *     returns com.my.project.service.rpc.client.UserList
     */
    @WebMethod(action = "http://service.project.my.com/user/list")
    @WebResult(name = "userList", partName = "userList")
    public UserList list();

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.my.project.service.rpc.client.User
     */
    @WebMethod(action = "http://service.project.my.com/user/login")
    @WebResult(name = "user", partName = "user")
    public User login(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password);

}
